server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;
    absolute_redirect off;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /en { return 301 /; }
    location = /en/ { return 301 /; }
    location = /ru { return 301 /ru/; }
}
